### ISSUE TITLE
An issue with Discord messages causing the server to crash

### ISSUE THREAD

**Issue by TianxSky** [BMathers35/CS2-ChatManager#1]
Some how when this plugin is loaded in with another one of my plugins that uses discord api the server will crash

**Comment by BMathers35** [comment]
We are not using the Discord Bot API, requests are made directly over HTTP. Can you share the error you got on your console before the crash? There are a few other people experiencing this issue, it might help me identify the source of the problem.

**Comment by BMathers35** [comment]
https://github.com/BMathers35/CS2-ChatManager/releases/tag/1.1.0
