### ISSUE TITLE
Junk messages in the console

### ISSUE THREAD

**Issue by Kl4rkx** [BMathers35/CS2-ChatManager#6]
### **How can I delete these messages in my server console? they fill my console with garbage**

![image](https://github.com/BMathers35/CS2-ChatManager/assets/90530426/8cfabc0f-7d65-4fba-b5a0-328bc52110ab)

**Comment by BMathers35** [comment]
If you remove line MuteManager.cs:93 and build, this message will not be sent in your console.
https://github.com/BMathers35/CS2-ChatManager/blob/master/ChatManager/MuteManager.cs#L93

**Comment by Kl4rkx** [comment]
Ty
